### ISSUE TITLE
Javascript not recognizing the graphJSON variable

### ISSUE THREAD

**Issue by lgerstner** [alanjones2/Flask-Plotly#1]
Hi there,

I am trying to duplicate the code you have created with a bit of a different example. When doing so there is an error in the javascript saying that a comma is expected after the creation of the graphs variable (the one referencing the graphJSON variable that's being passed from the render_template function). Any idea why this might be the case? 

Thank you!

**Comment by alanjones2** [comment]
If you post a code snippet, I might be able to help

**Comment by lgerstner** [comment]
I was helping someone with going through the example and it wasn't working on their machine. I duplicated your example on my machine and works perfect, so maybe a small bug or system set up on the other machine. Thanks again
